# Generated by Django 3.2.5 on 2021-07-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='surname',
            new_name='last_name',
        ),
    ]
