# Generated by Django 3.2.5 on 2021-08-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210803_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_enabled',
        ),
        migrations.AddField(
            model_name='user',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='accepted'),
        ),
    ]
