# Generated by Django 3.2.5 on 2021-08-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_squashed_0005_auto_20210803_1913'),
        ('mainpage', '0004_auto_20210804_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.department')),
            ],
            options={
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], max_length=15)),
                ('theory_weight', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('lab_weight', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('theory_limit', models.CharField(blank=True, max_length=4)),
                ('lab_limit', models.CharField(blank=True, max_length=4)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisiteClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_id', to='classes.classes')),
                ('prerequisite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_id', to='classes.classes')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_mark', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('lab_mark', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('final_mark', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('teaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.teaching')),
            ],
        ),
    ]
