# Generated by Django 3.2.5 on 2021-08-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_public_id',
            field=models.CharField(default='0001', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
