# Generated by Django 3.2.5 on 2021-08-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classes_class_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='class_public_id',
            new_name='public_id',
        ),
    ]
