# Generated by Django 3.2.5 on 2021-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_rename_class_public_id_classes_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='lab_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='theory_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
