# Generated by Django 3.2.5 on 2021-08-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20210812_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='lab_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='theory_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='prerequisiteclasses',
            unique_together={('class_id', 'prerequisite_id')},
        ),
    ]
