# Generated by Django 3.2.5 on 2021-08-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20210815_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsignup',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
