# Generated by Django 3.2.5 on 2021-08-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentstudents',
            old_name='student_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='departmentteachers',
            old_name='teacher_id',
            new_name='user_id',
        ),
    ]
