# Generated by Django 3.2.5 on 2021-08-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20210804_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(default='', max_length=512, unique=True),
            preserve_default=False,
        ),
    ]
