# Generated by Django 3.2.5 on 2021-08-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_department_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
