# Generated by Django 3.2.5 on 2021-08-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_department_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='semester',
            field=models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], default='first', max_length=15),
        ),
        migrations.AddField(
            model_name='department',
            name='state',
            field=models.CharField(choices=[('setup', 'Classes setup'), ('signup', 'Class signups'), ('mark', 'Class marks')], default='setup', max_length=6),
        ),
        migrations.AddField(
            model_name='department',
            name='year',
            field=models.CharField(default='2020', max_length=4),
            preserve_default=False,
        ),
    ]
