# Generated by Django 3.2.5 on 2021-08-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_auto_20210817_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
